version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  react:
    build:
      context: ./demo_frontend
      dockerfile: REACT_DOCKERFILE
    volumes:
      - ./demo_frontend/REACT_DOCKERFILE:/demo_frontend/REACT_DOCKERFILE
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  spring:
    build:
      context: ./demo_backend
      dockerfile: SPRING_DOCKERFILE
    volumes:
      - ./demo_backend/SPRING_DOCKERFILE:/demo_backend/SPRING_DOCKERFILE
    ports:
      - "8090:8090"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-conf/mysql_data:/var/lib/mysql
    networks:
      - mynetwork
